### ISSUE TITLE
Debug Assertion Failed!

### ISSUE THREAD

**Issue by 007basaran** [nathank33/KOServer#1]
Hello,

After some time this error is encountered while the files are running.

Bug : 

```
Debug Assertion Failed!

Program: ...RK\ZS_SRC\Source\GameServer\..\..\Server Files\GameServer.exe
File: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\xtree
Line: 229

Expression: map/set iterators incompatible

For information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts.
```

**Comment by devrimmehmet** [comment]
I wish it was updated and continued to improve ... Unfortunately I failed.
////////////////////////////////////////////////////////////////////////////////////
Keşke güncellense ve geliştirilmeye devam edilse... Ben başaramadım malesef.

**Comment by 007basaran** [comment]
TR : 

Birçok ayar denedim, fakat hiçbir şekilde çözüme ulaşamadım. Bu nedenden dolayı, hata bildirimi yaptım, nathank33'ün yardım etmesini bekleyeceğiz, bu süreçte de çözüm için araştırmaya devam edeceğiz.

EN: 

I've tried many settings, but I've never been able to find a solution. For this reason, I made an error statement, we will wait for nathank33 to help, and we will continue to search for a solution in this process.

**Comment by 007basaran** [comment]
Kardeşim hatayı geçici olarak çözmek için bu işlemleri gerçekleştir : 

1 - ) Gameserverdlg.cpp dosyasını aç : `g_pMain->m_pWorldEventManager->Tick();` bu alanı bulup başına // işareti koy. 

Yani bu şekilde gözükecek şekilde düzenle : `//g_pMain->m_pWorldEventManager->Tick();` 

2 - ) Worldeventmanager.cpp dosyasını aç bu alanı bul : 

```
for (auto it = m_startedEvents.begin(); it != m_startedEvents.end();) {
	auto eventId = it->first;
	auto event = it->second;
	if (std::chrono::system_clock::now() >= event->GetStartTime() + WORLD_EVENT_DURATION) {
	     StopEvent(eventId);
	} else {
	  it++;
      }
}
```

Bu kodla değiştir : 


```
auto it = m_startedEvents.begin();
while (it != m_startedEvents.end()) {
   auto eventId = it->first;
   auto event = it->second;
   if (std::chrono::system_clock::now() >= event->GetStartTime() + WORLD_EVENT_DURATION) {
	StopEvent(eventId);
    }
      else {
	it++;
      }
}

	/* Yukarıdaki while eklendi | kapatılanalan

		for (auto it = m_startedEvents.begin(); it != m_startedEvents.end();) {
			auto eventId = it->first;
			auto event = it->second;
			if (std::chrono::system_clock::now() >= event->GetStartTime() + WORLD_EVENT_DURATION) {
				StopEvent(eventId);
			} else {
				it++;
			}
		}
	
	*/

```
3 - ) Source dosyalarının olduğu yere git GameServer klasörü içerisine, GameServer.ini adlı boş bir metin belgesi oluştur. 

Tüm source dosyalarını temizleyip yeniden build et, Debug Assertion Failed hatasından geçici bir süreliğine kurtulursun, bifrost ve world event uygulaması ve daha fazlası için, yakında bu source dosyalarını kendime alıp oradan işlem yapacağım.

Sorunu anlattığım şekilde giderebilirsiniz, böylece geliştirme ve kodlar hakkında daha fazla bilgi sahibi olabilirsiniz.

İyi çalışmalar.
